Create Database EFC_Los_Mejores;
use EFC_Los_Mejores;



CREATE TABLE ALUMNOS
(
    ALU_RUT varchar(15) NOT NULL,
    ALU_CELULAR varchar(15) NOT NULL,
    ALU_MAIL VARCHAR (150) NOT NULL,
    PRIMARY KEY(ALU_RUT)
);


CREATE TABLE USUARIO
(
    USU_RUT varchar(15) not null,
    USU_NOMBRE varchar(100)not null,
    USU_MAIL varchar(150) not null,
    USU_PASSWORD VARCHAR(255) NOT NULL,
    PRIMARY KEY(USU_RUT)
   
);

CREATE TABLE INASISTENCIA
(
INA_CODIGO INT AUTO_INCREMENT NOT NULL,
INA_ASIGNATURA varchar(150) NOT NULL,
INA_FECHA DATETIME NOT NULL,
INA_ALUMNO varchar(15) not null,
INA_USUARIO varchar(15) not null,
INA_SECCION varchar(100) not null,
INA_ESTADO varchar(100) not null,
PRIMARY KEY(INA_CODIGO),
FOREIGN key(INA_USUARIO) REFERENCES USUARIO(USU_RUT),
FOREIGN key(INA_ALUMNO) REFERENCES ALUMNOS(ALU_RUT)
);

CREATE TABLE RESPUESTA
(
RES_CODIGO INT AUTO_INCREMENT NOT NULL,
RES_ACCION varchar(100) NOT NULL,
RES_RESPUESTA varchar(200) not null,
RES_INASISTENCIA int,
PRIMARY KEY(RES_CODIGO),
FOREIGN key(RES_INASISTENCIA) REFERENCES INASISTENCIA(INA_CODIGO)
);


    

